"""
Django settings for la27detailing_project project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#li3bq&+7c+3msfy3&8tk@n@&540j#5318ked7umh_i7m^99@l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'reservas_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'la27detailing_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'public')],  # ✅ Templates en public/
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',  # ✅ Agregado para debugging
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',  # ✅ Agregado para {% static %}
            ],
        },
    },
]

WSGI_APPLICATION = 'la27detailing_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'detailing27',
        'USER': 'root',
        'PASSWORD': 'facundo99',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ar'  # ✅ Cambiado a español de Argentina
TIME_ZONE = 'America/Argentina/Buenos_Aires'  # ✅ Zona horaria correcta

USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Donde Django buscará tus archivos estáticos adicionales (como los de public/)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'public'),
]

# Para producción (cuando ejecutes collectstatic)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================
# 🎨 CONFIGURACIÓN DE JAZZMIN
# ==============================
JAZZMIN_SETTINGS = {
    "site_title": "Panel LA27 Detailing",
    "site_header": "Administración LA27",
    "site_brand": "LA27 Detailing",
    "welcome_sign": "Bienvenido al Panel de Administración",
    
    # ✅ Modelos que SÍ existen en tu aplicación
    "search_model": [
        "reservas_app.Cliente",
        "reservas_app.Turnos", 
        "reservas_app.Trabajo",
        "reservas_app.TrabajoVehiculo",
    ],
    
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # ✅ Iconos para tus modelos reales
    "icons": {
        "reservas_app.Cliente": "fas fa-user",
        "reservas_app.Vehiculo": "fas fa-car",
        "reservas_app.Turnos": "fas fa-calendar-check",
        "reservas_app.Trabajo": "fas fa-wrench",
        "reservas_app.TrabajoVehiculo": "fas fa-clipboard-list",
        "reservas_app.Marca": "fas fa-tag",
        "auth.User": "fas fa-user-shield",
        "auth.Group": "fas fa-users",
    },
    
    # ✅ Enlaces personalizados en el menú superior
    "topmenu_links": [
        {"name": "Inicio", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Ver Calendario", "url": "/", "icon": "fas fa-calendar", "new_window": True},
    ],
    
    # Desactiva el constructor de UI para evitar problemas
    "show_ui_builder": False,
}

# (Opcional) 🎨 Ajustes de estilo visual
JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",  # Tema oscuro, ideal para LA27
    "navbar": "navbar-dark navbar-primary",
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_flat_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_child_indent": True,
    "brand_colour": "navbar-primary",
    "accent": "accent-lightblue",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
}