"""
Django settings for la27detailing_project project.

Generated by 'django-admin startproject' using Django 5.2.3.
"""
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-#li3bq&+7c+3msfy3&8tk@n@&540j#5318ked7umh_i7m^99@l'
DEBUG = True
ALLOWED_HOSTS = []

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'reservas_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'la27detailing_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'public')],  # Templates en public/
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'la27detailing_project.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'detailing27',
        'USER': 'root',
        'PASSWORD': 'facundo99',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'es-ar'
USE_I18N = True
USE_TZ = True
TIME_ZONE = 'America/Argentina/Buenos_Aires'

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'public')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================
# 🎨 CONFIGURACIÓN DE JAZZMIN
# ==============================
JAZZMIN_SETTINGS = {
    "site_title": "Panel LA27 Detailing",
    "site_header": "Administración LA27",
    "site_brand": "LA27 Detailing",
    "welcome_sign": "Bienvenido al Panel de Administración",
    "copyright": "© 2025 La 27 Detailing",

    # ✅ Logo
    "site_logo": "logola27.png",
    "login_logo": "logola27.png",
    "login_logo_dark": None,
    "site_logo_classes": "img-fluid",
    "site_logo_bg": "white",

    "search_model": [
        "reservas_app.Cliente",
        "reservas_app.Turnos",
        "reservas_app.Trabajo",
        "reservas_app.TrabajoVehiculo",
    ],

    "show_sidebar": True,
    "navigation_expanded": True,

    "icons": {
        "reservas_app.Cliente": "fas fa-user",
        "reservas_app.Vehiculo": "fas fa-car",
        "reservas_app.Turnos": "fas fa-calendar-check",
        "reservas_app.Trabajo": "fas fa-wrench",
        "reservas_app.TrabajoVehiculo": "fas fa-clipboard-list",
        "reservas_app.Marca": "fas fa-tag",
        "auth.User": "fas fa-user-shield",
        "auth.Group": "fas fa-users",
    },

    # ✅ Botones arriba
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "icon": "fas fa-chart-line"},
        {"name": "Volver al Sitio", "url": "/", "new_window": False, "icon": "fas fa-home"},
    ],

    "show_ui_builder": False,

}
# ==========================
# 🔐 LOGIN / LOGOUT SETTINGS
# ==========================

LOGOUT_REDIRECT_URL = '/admin/login/'
LOGIN_URL = '/admin/login/'
