# Generated by Django 5.2.5 on 2025-10-23 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0002_cliente_marca_trabajos_turnos_turnovehiculo_vehiculo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TurnoVehiculo',
            new_name='TrabajoVehiculo',
        ),
    ]
