# Generated by Django 5.2.5 on 2025-10-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0003_rename_turnovehiculo_trabajovehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajos',
            name='nombre_trabajo',
            field=models.CharField(max_length=100),
        ),
    ]
