# Generated by Django 5.2.5 on 2025-10-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0004_alter_trabajos_nombre_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajos',
            name='nombre_trabajo',
            field=models.CharField(max_length=150),
        ),
    ]
