# Generated by Django 5.2.5 on 2025-10-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0005_alter_trabajos_nombre_trabajo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajos',
            old_name='nombre_trabajo',
            new_name='descripcion_usuario',
        ),
    ]
