# Generated by Django 5.2.5 on 2025-10-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0006_rename_nombre_trabajo_trabajos_descripcion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajos',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
