# Generated by Django 5.2.5 on 2025-10-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0007_trabajos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajos',
            name='descripcion_usuario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='trabajos',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
