# Generated by Django 5.2.5 on 2025-10-29 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0008_alter_trabajos_descripcion_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_trabajo', models.CharField(max_length=100, verbose_name='Tipo de trabajo')),
                ('descripcion_usuario', models.TextField(blank=True, null=True, verbose_name='Detalles')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio ($)')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
            },
        ),
        migrations.RemoveField(
            model_name='trabajovehiculo',
            name='fecha_turno',
        ),
        migrations.AlterField(
            model_name='trabajovehiculo',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_app.trabajo'),
        ),
        migrations.DeleteModel(
            name='Trabajos',
        ),
    ]
