# Generated by Django 5.2.5 on 2025-11-04 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0009_trabajo_remove_trabajovehiculo_fecha_turno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='codigo_unico',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='trabajovehiculo',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_vehiculo', to='reservas_app.turnos'),
        ),
    ]
