# Generated by Django 5.2.5 on 2025-11-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0010_turnos_codigo_unico_alter_trabajovehiculo_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='descripcion_usuario',
        ),
        migrations.AddField(
            model_name='turnos',
            name='descripcion_usuario',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle del cliente'),
        ),
    ]
