# Generated by Django 5.2.5 on 2025-11-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0011_remove_trabajo_descripcion_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_whatsapp', models.CharField(help_text='Formato: +5493764123456 o 3764123456', max_length=20, verbose_name='Número de WhatsApp')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Configuración WhatsApp',
                'verbose_name_plural': 'Configuraciones WhatsApp',
            },
        ),
        migrations.AlterModelOptions(
            name='turnos',
            options={'ordering': ['-fecha_turno'], 'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.AddField(
            model_name='turnos',
            name='confirmado',
            field=models.BooleanField(default=False, verbose_name='Turno confirmado'),
        ),
        migrations.AddField(
            model_name='turnos',
            name='mensaje_enviado',
            field=models.BooleanField(default=False, verbose_name='WhatsApp enviado'),
        ),
    ]
