# Generated by Django 5.2.5 on 2025-11-18 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0012_configuracionwhatsapp_alter_turnos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='reservas_app.vehiculo'),
        ),
    ]
